#!/bin/bash

CPLEX_PATH="/opt/ibm/ILOG/CPLEX_Studio201"

export CPLEX="$CPLEX_PATH/cplex/lib/x86-64_linux/static_pic/libcplex.a"

if [ ! -e "$CPLEX" ]; then
    echo "$CPLEX is not the libcplex.a library file"
    exit 1
fi

export ILOCPLEX="$CPLEX_PATH/cplex/lib/x86-64_linux/static_pic/libilocplex.a"

if [ ! -e "$ILOCPLEX" ]; then
    echo "$ILOCPLEX is not the libilocplex.a library file"
    exit 1
fi

export CONCERT="$CPLEX_PATH/concert/lib/x86-64_linux/static_pic/libconcert.a"

if [ ! -e "$CONCERT" ]; then
    echo "$CONCERT is not the libconcert.a library file"
    exit 1
fi

export CPLEX_INCLUDES="$CPLEX_PATH/cplex/include"

if [ ! -e "$CPLEX_INCLUDES/ilcplex/ilocplex.h" ]; then
    echo "$CPLEX_INCLUDES does not point to a path containing ilcplex/ilocplex.h"
    exit 1
fi


export CONCERT_INCLUDES="$CPLEX_PATH/concert/include"

if [ ! -e "$CONCERT_INCLUDES/ilconcert/iloenv.h" ]; then
    echo "$CONCERT_INCLUDES does not point to a path containing ilconcert/iloenv.h"
    exit 1
fi

cd static_cplex
cmake -DCMAKE_VERBOSE_MAKEFILE=TRUE -DSTATIC_OPTIC=TRUE  -DCMAKE_BUILD_TYPE=Release -DCPLEX="$CPLEX" -DILOCPLEX="$ILOCPLEX" -DCONCERT="$CONCERT" -DCPLEX_INCLUDES="$CPLEX_INCLUDES" -DCONCERT_INCLUDES="$CONCERT_INCLUDES" ../src
